# Generated by Django 3.0.6 on 2020-05-06 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='ggca_rest.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('prompt', models.TextField()),
                ('activity', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='ggca_rest.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('activity_class', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='ggca_rest.Class')),
            ],
        ),
        migrations.CreateModel(
            name='StudentScreen',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('geogebra_data', models.TextField()),
                ('screen', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='ggca_rest.Screen')),
                ('student', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='ggca_rest.Student')),
            ],
        ),
    ]
