# Generated by Django 3.0.6 on 2020-05-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ggca_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ggca_rest.Activity'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='ggca_rest.Activity'),
        ),
        migrations.AlterField(
            model_name='student',
            name='activity_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='ggca_rest.Class'),
        ),
        migrations.AlterField(
            model_name='studentscreen',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_screens', to='ggca_rest.Screen'),
        ),
        migrations.AlterField(
            model_name='studentscreen',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='ggca_rest.Student'),
        ),
    ]
