# Generated by Django 3.0.6 on 2020-05-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggca_rest', '0002_auto_20200507_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscreen',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Empty'), (1, 'Started'), (2, 'Done')], default=0),
        ),
    ]
